### ISSUE TITLE
Conflict when markdown-it-sup and markdown-it-mathjax plugin enabled

### ISSUE THREAD

**Issue by BillChen2K** [hexojs/hexo-renderer-markdown-it#124]
Eg. markdown text: `$\forall i \ge 0, uv^iwx^iy \in L $`

And the rendered result is:

![image](https://user-images.githubusercontent.com/11037722/92114924-37c34980-ee24-11ea-81c8-6d8763e59499.png)

The symbol `^` in latex and symbol `^` in markdown will affect each other and equations won't be rendered properly. Can this be solved?

This is my markdown-it config file in hexo:

```

markdown:
  render:
    html: true
    xhtmlOut: false
    breaks: true
    linkify: true
    typographer: false
    quotes: '“”‘’'
  plugins:
    - markdown-it-abbr
    - markdown-it-footnote
    - markdown-it-ins
    # - markdown-it-sub
    # - markdown-it-sup
    - markdown-it-deflist
    - markdown-it-imsize
    - markdown-it-mark
    - markdown-it-regexp
    - markdown-it-mathjax
    - markdown-it-task-checkbox
    - name: markdown-it-emoji
      options:
        shortcuts: {}
  anchors:
    level: 2
    collisionSuffix: 'v'
    permalink: true
    permalinkClass: header-anchor
    permalinkSymbol: ''
```
