### ISSUE TITLE
Cannot GET / error

### ISSUE THREAD

**Issue by yihuajack** [hexojs/hexo-renderer-markdown-it#131]
I have uninstalled `hexo-renderer-ejs` and `hexo-renderer-marked`. I have installed `hexo-renderer-markdown-it`, `markdown-it-emoji`, and `markdown-it-task-lists`. I added the following sentences in Hexo `_config.yml`:
```
markdown:
  render:
    html: true
    xhtmlOut: false
    breaks: true
    linkify: true
    typographer: true
  plugins:
    - markdown-it-abbr
    - markdown-it-footnote
    - markdown-it-ins
    - markdown-it-sub
    - markdown-it-sup
    - markdown-it-emoji 
    - markdown-it-task-lists
  anchors:
    level: 2
    collisionSuffix: ''
    permalink: false,
    permalinkClass: 'header-anchor'
    permalinkSymbol: ''
    case: 0
    separator: ''
```
However, the editor gave syntax error "Incorrect type. Expected "string"." After I executed `hexo clean`, `hexo g`, and `hexo s`, I opened http://localhost:4000/ and the page only showed `Cannot GET /`.
I'm using theme "next". My blog website is https://yihuajack.github.io.
Is there any problem with the configuration?
