### ISSUE TITLE
Can't handle code in quote block correctly

### ISSUE THREAD

**Issue by wonter** [hexojs/hexo-renderer-markdown-it#136]
For this example:
```markdown
>quote text, quote text, quote text, quote text, quote text, quote text, quote text, quote text, quote text, quote text, 
>
>```
>code in quote
>code in quote
>code in quote
>code in quote
>```
>
>quote text, quote text, quote text, quote text, quote text, quote text, quote text, quote text, quote text, 
>
>
```

In [markdown-it demo](https://markdown-it.github.io/), it looks like this:

![image](https://user-images.githubusercontent.com/17780091/97399174-81617980-1927-11eb-9a47-0e5ddda20c7a.png)

But in my hexo site, it look like this:

![image](https://user-images.githubusercontent.com/17780091/97399217-9d651b00-1927-11eb-91c4-e22ddb89aedb.png)

So is this a renderer bug?

**Comment by wonter** [comment]
My _config.yml

```yaml
markdown:
  render:
    html: true
    xhtmlOut: false
    breaks: true
    linkify: false
    typographer: true
    quotes: '“”‘’'
  plugins:
    - markdown-it-abbr
    - markdown-it-emoji
    - markdown-it-kbd
    - markdown-it-sub
    - markdown-it-sup
    - markdown-it-task-checkbox
    - markdown-it-multimd-table
  anchors:
    level: 1
    collisionSuffix: 'v'
    permalink: true
    permalinkClass: header-anchor
    permalinkSymbol: ''
```
