### ISSUE TITLE
When using post asset folders, alternate texts are removed from images

### ISSUE THREAD

**Issue by bluebirch** [hexojs/hexo-renderer-markdown-it#205]
Configuration:

```yaml
markdown:
  images:
    post_asset: true
    prepend_root: true
```

Source `test.md`:

```markdown
![alt text](image.jpg)
```

Output:

```html
<p><img src="test/image.jpg" alt=""></p>
```
