### ISSUE TITLE
Footnotes failing, even after plugin configuration set in _config.yml

### ISSUE THREAD

**Issue by fusion809** [hexojs/hexo-renderer-markdown-it#37]
Hi,

I have added this:

``` yaml
markdown:
  plugins:
    - markdown-it-abbr
    - markdown-it-footnote
    - markdown-it-ins
    - markdown-it-sub
    - markdown-it-sup
```

to my `_config.yml` (i.e., the one in the top-level directory of my hexo-site). I also added:

``` json
    "hexo-renderer-markdown-it": "^3.4.1",
```

to the `dependencies:` section of my `package.json` file. Then I ran `npm install && npm uninstall hexo-renderer-marked`. I then started my Hexo server and my footnotes are being left un-rendered. That is, my in-text footnote is:

`[^1]`

and at the end of my post I have the footnote:

`[^1]: Which in itself is a variant, or distribution of Linux.`

they are left as is in the post. 

 Thanks for your time,
Brenton
