### ISSUE TITLE
does automatic-headline-ids feature works?

### ISSUE THREAD

**Issue by oupala** [hexojs/hexo-renderer-markdown-it#48]
Does [automatic-headline-ids](../wiki/Advanced-Configuration#automatic-headline-ids) feature works?

I tried to make it work by adding the corresponding configuration in `_config.yml` but I get no visible id in my html.

What could prevent this feature to work?

Does the plugin need specific plugins to be enabled?

**Comment by celsomiranda** [comment]
Can you post the specific `_config.yml` configuration you used?
It should work without activating any plugins.

**Comment by oupala** [comment]
Here is my config file:

```yml
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: just a title
subtitle:
description: a simple blog
author:
language: fr
timezone: Europe/Paris

# redirections
include:
  - .htaccess

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://blog.example.org
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 1
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: DD-MM-YYYY
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Markdown-it config
## Docs: https://github.com/celsomiranda/hexo-renderer-markdown-it/wiki
markdown:
  render:
    html: true
    xhtmlOut: false
    breaks: false
    linkify: true
    typographer: true
    quotes: '“”‘’'
  plugins:
    - markdown-it-abbr
    - markdown-it-footnote
  anchors:
    # Minimum level for ID creation. (Ex. h2 to h6)
    level: 2
    # A suffix that is prepended to the number given if the ID is repeated.
    collisionSuffix: 'v'
    # If `true`, creates an anchor tag with a permalink besides the heading.
    permalink: true
    # Class used for the permalink anchor tag.
    permalinkClass: header-anchor
    # The symbol used to make the permalink
    permalinkSymbol: ¶

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: bootstrap-blog

theme_config:
  # Header
  navbar_brand: false
  menu:
    accueil: index.html
    archives: archives/
    rss: /atom.xml

  # Content
  excerpt_link: Read More
  fancybox: true

  # Sidebar
  widgets:
  - tagcloud
  - archive
  - about         # See also: `about_content`
  about_widget_content: >
    <p>to contact me, send an email to blog@example.org</p>

  # widget behavior
  archive_type: 'monthly'
  show_count: true

  # Miscellaneous
  google_analytics:
  favicon:
  twitter_id:
  google_plus:
  fb_admins:
  fb_app_id:

# table of content
toc:
  maxdepth: 3

# RSS feed
feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content: true

# Server
server:
  port: 8080

alias:
  2015/05/03/old-post/: 2015/10/03/new-post/

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type:
```

**Comment by elboletaire** [comment]
I'm also experiencing issues with this feature.... sometimes works and sometimes it does not, without any log in the console (I execute both `serve` and `generate` with the `--debug` arg).

**Comment by oupala** [comment]
In fact, it works except that there is a conflict with [hexo-toc](/bubkoo/hexo-toc/), see [issue #20](/bubkoo/hexo-toc/issues/20) of hexo-toc.

**Comment by noraj** [comment]
Yes and also try `hexo clean` before rendering if you installed or uninstalled some dependencies.

**Comment by oupala** [comment]
There is a conflict between this plugin and another plugin. I don't think we should really close this issue.

The conflict should be resolved before closing the issue.

**Comment by noraj** [comment]
The problem is from hexo-toc side but I don't think theu will fix it soon if ever. The project seems unmaintained.

**Comment by oupala** [comment]
If the problem is on hexo-toc side, let's close this issue.

I'll ask hexo-toc if it is still maintained. By the way, does anyone know an alternative to hexo-toc?

**Comment by noraj** [comment]
@oupala Look at my issue here: https://github.com/hexojs/hexo-renderer-markdown-it/issues/53

**Comment by curbengh** [comment]
headline ID is automatically added and it [should work](https://github.com/hexojs/hexo-renderer-markdown-it/blob/5508dc44204b3737d2e49af9b103a1a814b0d282/test/index.js#L167).

**Comment by oupala** [comment]
I tested hexo-renderer-markdown-it v4.0.0 and it still does not render the headlines.

I searched but I really don't understand why...

Can anyone have a look at my configuration files?

package.json:

```
{
  "name": "hexo-project",
  "version": "0.1.0",
  "private": true,
  "hexo": {
    "version": "4.0.0"
  },
  "scripts": {
    "start": "npm run serve",
    "postinstall": "git submodule init && git submodule update",
    "exec": "node_modules/.bin/hexo",
    "generate": "npm run exec generate",
    "serve": "npm run exec serve",
    "dev": "npm run exec serve -- --draft"
  },
  "dependencies": {
    "hexo": "^4.0.0",
    "hexo-generator-alias": "^0.1.3",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-feed": "^2.1.1",
    "hexo-generator-index": "^1.0.0",
    "hexo-generator-tag": "^1.0.0",
    "hexo-inject": "^1.0.0",
    "hexo-renderer-ejs": "^1.0.0",
    "hexo-renderer-markdown-it": "^4.0.0",
    "hexo-renderer-stylus": "^1.1.0",
    "hexo-server": "^1.0.0",
    "hexo-tag-easy-charts": "^0.3.0"
  }
}
```

_config.yml:

```
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: site title
subtitle:
description: site description
author:
language: en
timezone: Europe/London

# redirections
include:
  - .htaccess

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://blog.example.org
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 1
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: DD-MM-YYYY
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Markdown-it config
## Docs: https://github.com/celsomiranda/hexo-renderer-markdown-it/wiki
markdown:
  render:
    html: true
    xhtmlOut: false
    breaks: false
    linkify: true
    typographer: true
    quotes: '“”‘’'
  plugins:
  anchors:
    # Minimum level for ID creation. (Ex. h2 to h6)
    level: 1
    # A suffix that is prepended to the number given if the ID is repeated.
    collisionSuffix: 'v'
    # If `true`, creates an anchor tag with a permalink besides the heading.
    permalink: false
    # Class used for the permalink anchor tag.
    permalinkClass: header-anchor
    # The symbol used to make the permalink
    permalinkSymbol: ¶

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: bootstrap-blog

theme_config:
  # Header
  navbar_brand: false
  menu:
    accueil: index.html
    archives: archives/
    rss: /atom.xml

  # Content
  excerpt_link: Read More
  fancybox: true

  # Sidebar
  widgets:
  - tagcloud
  - archive
  - about         # See also: `about_content`
  about_widget_content: >
    <p>mail me at test@example.org</p>

  # widget behavior
  archive_type: 'monthly'
  show_count: true

  # Miscellaneous
  google_analytics:
  favicon:
  twitter_id:
  google_plus:
  fb_admins:
  fb_app_id:

# table of content
#toc:
#  maxdepth: 3

# RSS feed
feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content: true

# Server
server:
  port: 8080

alias:
  2017/05/03/old-url/: 2017/10/03/old_url/

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type:
```

Have I missed anything?

**Comment by curbengh** [comment]
I tested your config:

``` yml
markdown:
  render:
    html: true
    xhtmlOut: false
    breaks: false
    linkify: true
    typographer: true
    quotes: '“”‘’'
  plugins:
  anchors:
    # Minimum level for ID creation. (Ex. h2 to h6)
    level: 1
    # A suffix that is prepended to the number given if the ID is repeated.
    collisionSuffix: 'v'
    # If `true`, creates an anchor tag with a permalink besides the heading.
    permalink: false
    # Class used for the permalink anchor tag.
    permalinkClass: header-anchor
    # The symbol used to make the permalink
    permalinkSymbol: ¶
```

I can see id class in the resulting html.
