### ISSUE TITLE
hexo-renderer-markdown-it中如何解决markdown和mathjax之间的冲突呢？

### ISSUE THREAD

**Issue by weidongzhou1994** [hexojs/hexo-renderer-markdown-it#74]
在使用hexo-renderer-markdown-it的过程中，数学公式的输入使我头疼，如$ \sum_{i=0}^{n}i^2 $不能在hexo显示出正确的格式，该怎么解决呢？

**Comment by stevenjoezhang** [comment]
用`\`转义
```
$ \sum_{i=0}^{n}i^2 $
$ \sum\_{i=0}^{n}i^2 $
```

**Comment by Qinka** [comment]
我从 https://github.com/classeur/markdown-it-mathjax fork了一份，然后进行了修改 https://github.com/Qinka/markdown-it-mathjax-skip ，但是没有传到 npm 上，依赖加上后在 plugins 中加上 `markdown-it-mathjax-skip` 就好了。 （原始的那个没办法被作为插件使用，我修改的内容只是让那个可以作为插件使用）

```yaml
markdown:
  render:
    html: true
    xhtmlOut: false
    breaks: false
    linkify: true
    typographer: true
    quotes: '“”‘’'
  plugins:
    - markdown-it-mathjax-skip
    - markdown-it-abbr
    - markdown-it-footnote
    - markdown-it-ins
    - markdown-it-emoji
    - markdown-it-sub
    - markdown-it-sup
  anchors:
    level: 2
    collisionSuffix: ''
    permalink: false
    permalinkClass: 'header-anchor'
    permalinkSide: 'left'
    permalinkSymbol: '¶'
    case: 0
    separator: ''
```
